Updated statuses for processes with timeout, added a way to edit exis…
mpcmf/processManager pull request #1
Opened 2019-01-16 07:44 UTC by Igorut

…t text in field in process edit ('Tab' button). In developing a way to read the log of bots

2019-01-16 07:57 UTC, alexbilevskiy approved these changes

2019-01-16 09:11 UTC, ildarsaitkulov requested changes

2019-01-16 09:11 UTC, ildarsaitkulov commented on apps/processHandler/commands/processHandler/processHandlerAdmin.php
> +                        $process['state'] = "timeout {$timeAfterLastUpdate} seconds";
Не надо переопределять `$process['state']`.  Нам же нужно только отобразить, значит измениться должен только `$title`, который служит для отображения

2019-01-16 10:09 UTC, ildarsaitkulov approved these changes

2019-01-22 12:27 UTC, alexbilevskiy commented on apps/processHandler/commands/processHandler/processHandlerAdmin.php
> +            $title1 = $server1['host'];
кажется тут достаточно `return ($title1 < $title2);`

2019-02-04 14:27 UTC, merged