Updating manager
mpcmf/processManager pull request #9
Opened 2019-08-22 11:28 UTC by raymanovg

2019-08-22 14:45 UTC, alexbilevskiy commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
зачем ты тут к строке приводишь? А потом при сохранении будет приводиться обратно из строки в mongoId?

2019-08-22 14:54 UTC, raymanovg commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Да при сохранении будет обратно в mongoId. Смысла нету ввиде объекта его держать, в нескольких местах он еще нужен как строка.

2019-08-22 15:29 UTC, alexbilevskiy commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Ну а если с другой стороны посмотреть, какой смысл приводить объект в строку и назад? Это лишние операции, к тому же нарушающие целостность объекта:
```
> $id = new \MongoId();
> $copy = new \MongoId((string) $id);
> var_dump($id === $copy);
bool(false)
```

Кстати, к строке ты тоже приводишь не совсем правильно, принято использовать `$mongoId->{'$id'}`,  и тогда всё будет выглядеть логично

2019-08-23 07:38 UTC, raymanovg commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Неудачный немного пример со сравнением объектов mongoId. Два разных объекта никогда не будут равны
`
class foo {}
$one = new foo();
$two = new foo();
var_dump($one === $two); // bool(false)
`

Согласен, будет лучше если все таки будем хранить объект и будем дергать свойство `$mongoId->{'$id'}` когда нужно строковое значение.

2019-08-23 07:52 UTC, alexbilevskiy commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Ну дак пример специально и взят такой, это нормально что два объекта не равны, поэтому и не надо пересоздавать их)

2019-08-23 08:08 UTC, raymanovg commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Если будем юзать объекты, нужно будет переделавать логику методов api... они ждут mongoId в виде стороки и возвращают строку. @alexbilevskiy, делать?

2019-08-23 08:15 UTC, alexbilevskiy commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
апи в теории должно уметь работать по http, а там объекты невозможны, поэтому там как раз можно оставить строки

2019-08-27 08:53 UTC, gilberg-vrn commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
{'$id'}? Это где такое принято?

2019-08-27 08:56 UTC, alexbilevskiy commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
@gilberg-vrn В нашем проекте?

2019-08-27 09:03 UTC, gilberg-vrn requested changes

2019-08-27 09:03 UTC, gilberg-vrn commented on apps/processHandler/libraries/processManagerCliMenu/changeSortControlItem.php
> +         $this->updateHeader($sortMenu, $menu);
.

2019-08-27 09:06 UTC, gilberg-vrn commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Фигово, если так... Лучше приведение к строке, чем этот изврат, с обращением к внутренней структуре, которая к тому же должна быть protected и вообще может называться не I'd или измениться в будущем

2019-08-27 09:38 UTC, raymanovg commented on apps/processHandler/libraries/processManagerCliMenu/changeSortControlItem.php
> +         $this->updateHeader($sortMenu, $menu);
fixed

2019-08-27 09:43 UTC, alexbilevskiy commented on apps/processHandler/libraries/processManagerCliMenu/processNewControllerItem.php
> +            '_id' => (string) (new \MongoId()),
Ну точно так же в будущем может измениться метод приведения к строке) 

Забыл сказать, мы все равно не стали так делать, потому что объект оказалось слишком сложно прокинуть, это обсуждение чисто факультативное.

2019-08-28 12:35 UTC, gilberg-vrn approved these changes

2019-09-02 12:27 UTC, merged